### ISSUE TITLE
reference importer stopped working in Alfred 3.5.1

### ISSUE THREAD

**Issue by tobiasgerstenberg** [andrewning/alfred-workflows-scientific#8]
The reference importer stopped working for me with the most recent version of Alfred 3 (3.5.1, Build 883). It's a bummer since I love the tool and use it a ton. Any suggestions on how to fix things (or help with fixing) would be appreciated.

**Comment by andrewning** [comment]
Yeah I’ve noticed too. Bummer. Crossref is complaining about a rate limit. I don’t think I’m using the latest API so hopefully updating that would fix it, but I won’t have any time to work on it until the winter holidays. It could probably be temporarily fixed by not checking continuously but only after a special character (which is what I do with gsref).

**Comment by tobiasgerstenberg** [comment]
Unfortunately, gsref doesn't work either anymore. So I don't think that's the issue. Looking forward to the fix as a Christmas present ;)

**Comment by andrewning** [comment]
I've fixed crossref.  The issues with gsref is completely unrelated, but I haven't had time to take on that one yet.

**Comment by tobiasgerstenberg** [comment]
great! thanks for the Christmas present :)
